<?php

namespace Database\Seeders;

use App\Models\Booking;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BookingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $bookings = [
            [
                'id' => 34,
                'branch_id' => 6,
                'name' => 'SEAN',
                'phone' => '0882014878',
                'booking_date' => '2025-08-18',
                'booking_time' => '09:00:00',
                'note' => null,
                'image' => null,
                'know_through' => '1',
                'payment' => '15',
                'status' => 'confirmed',
                'created_at' => '2025-08-17 08:43:42',
                'updated_at' => '2025-08-18 09:21:33',
            ],
            [
                'id' => 27,
                'branch_id' => 1,
                'name' => 'Ban Sreymeas',
                'phone' => '0969979620',
                'booking_date' => '2025-08-17',
                'booking_time' => '13:00:00',
                'note' => null,
                'image' => null,
                'know_through' => '1',
                'payment' => '106',
                'status' => 'confirmed',
                'created_at' => '2025-08-16 12:55:26',
                'updated_at' => '2025-08-17 13:18:48',
            ],
            [
                'id' => 32,
                'branch_id' => 6,
                'name' => 'MALIN',
                'phone' => '087889808',
                'booking_date' => '2025-08-17',
                'booking_time' => '13:00:00',
                'note' => '3PEOPLES ADD HAIR CUT =perm166$+color 130$+color 74$+perm 80$',
                'image' => null,
                'know_through' => '1',
                'payment' => '457',
                'status' => 'confirmed',
                'created_at' => '2025-08-17 07:25:26',
                'updated_at' => '2025-08-18 09:24:00',
            ],
            [
                'id' => 33,
                'branch_id' => 1,
                'name' => 'Kao meiling',
                'phone' => '0967996616',
                'booking_date' => '2025-08-17',
                'booking_time' => '14:00:00',
                'note' => 'គាត់រវល់',
                'image' => null,
                'know_through' => '1',
                'payment' => '18',
                'status' => 'confirmed',
                'created_at' => '2025-08-17 08:39:59',
                'updated_at' => '2025-08-17 13:17:18',
            ],
            [
                'id' => 9,
                'branch_id' => 1,
                'name' => 'ណាណា',
                'phone' => '016815005',
                'booking_date' => '2025-08-15',
                'booking_time' => '15:00:00',
                'note' => 'សុំឲ្យជាងជួយមើលម៉ូតសក់។',
                'image' => null,
                'know_through' => '1',
                'payment' => '50',
                'status' => 'confirmed',
                'created_at' => '2025-08-15 08:40:10',
                'updated_at' => '2025-08-15 13:57:37',
            ],
            [
                'id' => 10,
                'branch_id' => 6,
                'name' => 'Fang',
                'phone' => '0975252709',
                'booking_date' => '2025-08-15',
                'booking_time' => '14:00:00',
                'note' => null,
                'image' => null,
                'know_through' => '1',
                'payment' => '18',
                'status' => 'confirmed',
                'created_at' => '2025-08-15 09:17:31',
                'updated_at' => '2025-08-15 14:02:41',
            ],
            [
                'id' => 11,
                'branch_id' => 5,
                'name' => 'Chanlyka',
                'phone' => '012685354',
                'booking_date' => '2025-08-15',
                'booking_time' => '13:00:00',
                'note' => null,
                'image' => null,
                'know_through' => '1',
                'payment' => '88',
                'status' => 'confirmed',
                'created_at' => '2025-08-15 09:28:12',
                'updated_at' => '2025-08-16 06:23:07',
            ],
            [
                'id' => 12,
                'branch_id' => 1,
                'name' => 'AH KA',
                'phone' => '070966599',
                'booking_date' => '2025-08-15',
                'booking_time' => '13:00:00',
                'note' => null,
                'image' => null,
                'know_through' => '1',
                'payment' => '13',
                'status' => 'confirmed',
                'created_at' => '2025-08-15 09:31:42',
                'updated_at' => '2025-08-15 13:57:14',
            ],
            [
                'id' => 13,
                'branch_id' => 6,
                'name' => 'Mey',
                'phone' => '069999905',
                'booking_date' => '2025-08-15',
                'booking_time' => '14:00:00',
                'note' => null,
                'image' => null,
                'know_through' => '1',
                'payment' => '15',
                'status' => 'confirmed',
                'created_at' => '2025-08-15 10:37:07',
                'updated_at' => '2025-08-15 14:01:54',
            ],
            [
                'id' => 14,
                'branch_id' => 5,
                'name' => 'Sokunthy',
                'phone' => '092389610',
                'booking_date' => '2025-08-15',
                'booking_time' => '15:00:00',
                'note' => null,
                'image' => null,
                'know_through' => '1',
                'payment' => '88',
                'status' => 'confirmed',
                'created_at' => '2025-08-15 10:45:15',
                'updated_at' => '2025-08-16 06:23:24',
            ],
            [
                'id' => 15,
                'branch_id' => 1,
                'name' => 'Sokdearlist',
                'phone' => '069889993',
                'booking_date' => '2025-08-16',
                'booking_time' => '15:00:00',
                'note' => null,
                'image' => null,
                'know_through' => '1',
                'payment' => '25',
                'status' => 'confirmed',
                'created_at' => '2025-08-15 12:40:25',
                'updated_at' => '2025-08-16 13:08:24',
            ],
            [
                'id' => 28,
                'branch_id' => 2,
                'name' => 'name china',
                'phone' => '086221616',
                'booking_date' => '2025-08-17',
                'booking_time' => '14:00:00',
                'note' => null,
                'image' => null,
                'know_through' => '1',
                'payment' => '48',
                'status' => 'confirmed',
                'created_at' => '2025-08-16 13:09:13',
                'updated_at' => '2025-08-17 13:18:36',
            ],
            [
                'id' => 17,
                'branch_id' => 4,
                'name' => 'Long sonitha',
                'phone' => '060436656',
                'booking_date' => '2025-08-16',
                'booking_time' => '10:00:00',
                'note' => null,
                'image' => null,
                'know_through' => '1',
                'payment' => '88',
                'status' => 'confirmed',
                'created_at' => '2025-08-15 14:51:34',
                'updated_at' => '2025-08-16 13:37:34',
            ],
            [
                'id' => 18,
                'branch_id' => 1,
                'name' => 'ឈ្មោះនីតា',
                'phone' => '0884485874',
                'booking_date' => '2025-08-16',
                'booking_time' => '12:00:00',
                'note' => null,
                'image' => null,
                'know_through' => '1',
                'payment' => '18',
                'status' => 'confirmed',
                'created_at' => '2025-08-16 07:40:22',
                'updated_at' => '2025-08-16 10:30:27',
            ],
            [
                'id' => 19,
                'branch_id' => 4,
                'name' => 'Pich',
                'phone' => '077444260',
                'booking_date' => '2025-08-16',
                'booking_time' => '13:00:00',
                'note' => 'perm lash&eyelash=33.9$',
                'image' => null,
                'know_through' => '1',
                'payment' => '34',
                'status' => 'confirmed',
                'created_at' => '2025-08-16 08:47:33',
                'updated_at' => '2025-08-16 13:36:47',
            ],
            [
                'id' => 20,
                'branch_id' => 4,
                'name' => 'Pich',
                'phone' => '077444260',
                'booking_date' => '2025-08-16',
                'booking_time' => '13:00:00',
                'note' => 'ឆែកសក់ចង់អ៊ុត',
                'image' => null,
                'know_through' => '1',
                'payment' => '88',
                'status' => 'confirmed',
                'created_at' => '2025-08-16 08:47:34',
                'updated_at' => '2025-08-17 06:47:43',
            ],
            [
                'id' => 21,
                'branch_id' => 1,
                'name' => 'Votey',
                'phone' => '087416468',
                'booking_date' => '2025-08-16',
                'booking_time' => '12:00:00',
                'note' => null,
                'image' => null,
                'know_through' => '1',
                'payment' => '10',
                'status' => 'confirmed',
                'created_at' => '2025-08-16 08:53:32',
                'updated_at' => '2025-08-16 10:29:50',
            ],
            [
                'id' => 22,
                'branch_id' => 4,
                'name' => 'JOULINE HOPE',
                'phone' => '087785298',
                'booking_date' => '2025-08-16',
                'booking_time' => '14:00:00',
                'note' => null,
                'image' => null,
                'know_through' => '1',
                'payment' => '25',
                'status' => 'confirmed',
                'created_at' => '2025-08-16 10:06:53',
                'updated_at' => '2025-08-16 11:41:11',
            ],
            [
                'id' => 23,
                'branch_id' => 4,
                'name' => 'THEARIT THEARY',
                'phone' => '077916696',
                'booking_date' => '2025-08-16',
                'booking_time' => '15:00:00',
                'note' => null,
                'image' => null,
                'know_through' => '1',
                'payment' => '18',
                'status' => 'confirmed',
                'created_at' => '2025-08-16 10:33:39',
                'updated_at' => '2025-08-16 13:35:17',
            ],
            [
                'id' => 29,
                'branch_id' => 3,
                'name' => 'Chhim Soknita',
                'phone' => '011477335',
                'booking_date' => '2025-08-17',
                'booking_time' => '10:00:00',
                'note' => 'អ៊ុតត្រង់Botox ហើយកាត់សក់ (អ៊ុតអត់បានទិញកញ្ចប់ស្ប៉ាវិញ)',
                'image' => null,
                'know_through' => '1',
                'payment' => '80',
                'status' => 'confirmed',
                'created_at' => '2025-08-16 14:17:36',
                'updated_at' => '2025-08-17 13:18:10',
            ],
            [
                'id' => 35,
                'branch_id' => 6,
                'name' => 'B KUNTHY',
                'phone' => '077814081',
                'booking_date' => '2025-08-17',
                'booking_time' => '15:00:00',
                'note' => null,
                'image' => null,
                'know_through' => '1',
                'payment' => '76',
                'status' => 'confirmed',
                'created_at' => '2025-08-17 10:48:02',
                'updated_at' => '2025-08-18 09:20:33',
            ],
            [
                'id' => 36,
                'branch_id' => 4,
                'name' => 'Sothean',
                'phone' => '017222306',
                'booking_date' => '2025-08-18',
                'booking_time' => '10:00:00',
                'note' => null,
                'image' => null,
                'know_through' => '1',
                'payment' => '176',
                'status' => 'confirmed',
                'created_at' => '2025-08-18 06:08:49',
                'updated_at' => '2025-08-20 06:14:26',
            ],
            [
                'id' => 37,
                'branch_id' => 5,
                'name' => 'ស្រីនាង',
                'phone' => '010567856',
                'booking_date' => '2025-08-18',
                'booking_time' => '11:00:00',
                'note' => 'អ៊ុតអត់បាន កក់កាត់វិញ',
                'image' => null,
                'know_through' => '1',
                'payment' => '17',
                'status' => 'confirmed',
                'created_at' => '2025-08-18 06:44:57',
                'updated_at' => '2025-08-20 06:15:22',
            ],
            [
                'id' => 38,
                'branch_id' => 2,
                'name' => 'Hong Sivchhing',
                'phone' => '017527070',
                'booking_date' => '2025-08-18',
                'booking_time' => '13:00:00',
                'note' => null,
                'image' => null,
                'know_through' => '1',
                'payment' => '18',
                'status' => 'confirmed',
                'created_at' => '2025-08-18 07:00:08',
                'updated_at' => '2025-08-20 06:15:50',
            ],
            [
                'id' => 39,
                'branch_id' => 6,
                'name' => 'Pin',
                'phone' => '069618632',
                'booking_date' => '2025-08-18',
                'booking_time' => '18:00:00',
                'note' => null,
                'image' => null,
                'know_through' => '1',
                'payment' => '30',
                'status' => 'confirmed',
                'created_at' => '2025-08-18 10:48:26',
                'updated_at' => '2025-08-20 06:16:33',
            ],
            [
                'id' => 40,
                'branch_id' => 5,
                'name' => 'Sokunthy',
                'phone' => '092389610',
                'booking_date' => '2025-08-18',
                'booking_time' => '15:00:00',
                'note' => 'បង ខ្ញ៉ំស៉ំកក់ម៉ោង 3:30',
                'image' => null,
                'know_through' => '1',
                'payment' => '88',
                'status' => 'confirmed',
                'created_at' => '2025-08-18 11:24:20',
                'updated_at' => '2025-08-20 06:17:02',
            ],
            [
                'id' => 41,
                'branch_id' => 6,
                'name' => 'b kim',
                'phone' => '017878787',
                'booking_date' => '2025-08-19',
                'booking_time' => '14:00:00',
                'note' => 'ណាត់បងថុនា fri b CEO',
                'image' => null,
                'know_through' => '1',
                'payment' => '16',
                'status' => 'confirmed',
                'created_at' => '2025-08-18 13:18:56',
                'updated_at' => '2025-08-20 06:17:50',
            ],
            [
                'id' => 42,
                'branch_id' => 1,
                'name' => 'យ៉េន សុគា',
                'phone' => '068722001',
                'booking_date' => '2025-08-23',
                'booking_time' => '10:00:00',
                'note' => null,
                'image' => null,
                'know_through' => null,
                'payment' => null,
                'status' => 'processing',
                'created_at' => '2025-08-19 07:08:11',
                'updated_at' => '2025-08-19 07:08:11',
            ],
            [
                'id' => 43,
                'branch_id' => 6,
                'name' => 'Chakrya',
                'phone' => '017366626',
                'booking_date' => '2025-08-19',
                'booking_time' => '13:00:00',
                'note' => 'រវល់',
                'image' => null,
                'know_through' => '1',
                'payment' => null,
                'status' => 'cancel',
                'created_at' => '2025-08-19 07:16:04',
                'updated_at' => '2025-08-20 06:19:25',
            ],
            [
                'id' => 52,
                'branch_id' => 2,
                'name' => 'Sreyleak',
                'phone' => '017667868',
                'booking_date' => '2025-08-24',
                'booking_time' => '10:00:00',
                'note' => null,
                'image' => null,
                'know_through' => null,
                'payment' => null,
                'status' => 'processing',
                'created_at' => '2025-08-20 06:40:18',
                'updated_at' => '2025-08-20 06:40:18',
            ],
            [
                'id' => 46,
                'branch_id' => 6,
                'name' => 'Muteta',
                'phone' => '+855 98 829 000',
                'booking_date' => '2025-08-19',
                'booking_time' => '14:00:00',
                'note' => 'Booked 1:30pm \r\nតរោមភ្នែក និង កាត់សក់',
                'image' => null,
                'know_through' => null,
                'payment' => null,
                'status' => 'processing',
                'created_at' => '2025-08-19 09:16:21',
                'updated_at' => '2025-08-19 09:16:21',
            ],
            [
                'id' => 48,
                'branch_id' => 1,
                'name' => 'Lim muyleng',
                'phone' => '069993000',
                'booking_date' => '2025-08-21',
                'booking_time' => '15:00:00',
                'note' => null,
                'image' => null,
                'know_through' => null,
                'payment' => null,
                'status' => 'processing',
                'created_at' => '2025-08-19 11:19:11',
                'updated_at' => '2025-08-19 11:19:11',
            ],
            [
                'id' => 49,
                'branch_id' => 6,
                'name' => 'Pisey',
                'phone' => '069606628',
                'booking_date' => '2025-08-19',
                'booking_time' => '17:00:00',
                'note' => null,
                'image' => null,
                'know_through' => '1',
                'payment' => '18',
                'status' => 'confirmed',
                'created_at' => '2025-08-19 13:17:42',
                'updated_at' => '2025-08-20 06:23:06',
            ],
            [
                'id' => 50,
                'branch_id' => 4,
                'name' => 'Perng Jing Jing',
                'phone' => '0963581888',
                'booking_date' => '2025-08-22',
                'booking_time' => '15:00:00',
                'note' => null,
                'image' => null,
                'know_through' => '1',
                'payment' => null,
                'status' => 'processing',
                'created_at' => '2025-08-19 17:47:58',
                'updated_at' => '2025-08-20 06:10:06',
            ],
            [
                'id' => 51,
                'branch_id' => 6,
                'name' => 'SreyRoth',
                'phone' => '015718502',
                'booking_date' => '2025-08-21',
                'booking_time' => '09:00:00',
                'note' => null,
                'image' => null,
                'know_through' => null,
                'payment' => null,
                'status' => 'processing',
                'created_at' => '2025-08-19 20:58:49',
                'updated_at' => '2025-08-19 20:58:49',
            ],
            [
                'id' => 53,
                'branch_id' => 2,
                'name' => 'Dana',
                'phone' => '093389678',
                'booking_date' => '2025-08-20',
                'booking_time' => '11:00:00',
                'note' => null,
                'image' => null,
                'know_through' => null,
                'payment' => null,
                'status' => 'processing',
                'created_at' => '2025-08-20 06:43:57',
                'updated_at' => '2025-08-20 06:43:57',
            ],
            [
                'id' => 54,
                'branch_id' => 6,
                'name' => 'Ariya',
                'phone' => '061929897',
                'booking_date' => '2025-08-20',
                'booking_time' => '11:00:00',
                'note' => null,
                'image' => null,
                'know_through' => null,
                'payment' => null,
                'status' => 'processing',
                'created_at' => '2025-08-20 06:48:59',
                'updated_at' => '2025-08-20 06:48:59',
            ],
            [
                'id' => 55,
                'branch_id' => 4,
                'name' => 'Lyn',
                'phone' => '+85570868786',
                'booking_date' => '2025-08-20',
                'booking_time' => '15:00:00',
                'note' => null,
                'image' => null,
                'know_through' => null,
                'payment' => null,
                'status' => 'processing',
                'created_at' => '2025-08-20 07:08:54',
                'updated_at' => '2025-08-20 07:08:54',
            ],
            [
                'id' => 56,
                'branch_id' => 4,
                'name' => 'b yana',
                'phone' => '010356168',
                'booking_date' => '2025-08-20',
                'booking_time' => '15:00:00',
                'note' => null,
                'image' => null,
                'know_through' => null,
                'payment' => null,
                'status' => 'processing',
                'created_at' => '2025-08-20 09:58:01',
                'updated_at' => '2025-08-20 09:58:01',
            ],
        ];

        foreach ($bookings as $booking) {
            Booking::updateOrCreate(
                ['id' => $booking['id']], // Match by ID
                $booking // Data to insert or update
            );
        }
    }
}
